function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  stairs x
%  Y1:  stairs y

%  Auto-generated by MATLAB on 27-Jan-2020 09:12:44

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stairs
stairs(X1,Y1,...
    'MarkerFaceColor',[0.501960813999176 0.501960813999176 0.501960813999176],...
    'MarkerEdgeColor',[0 0 0],...
    'MarkerSize',20,...
    'Marker','pentagram',...
    'LineWidth',2,...
    'LineStyle','--',...
    'Color',[1 0 0]);

box(axes1,'on');
